In [1]:
import numpy as np
import pandas as pd

# Arrays Easy

Function the return sorted squares values of a sorted array

In [2]:
#O(n log(n)) time | O(n) space
def sortedSquaredArray(array):
    array = [x*x for x in array]
    array.sort()
    return array

In [3]:
a = [1, 2, 3, 5, 6, 8, 9]
b = [-5, -4, -3, -2, -1]
print(sortedSquaredArray(b))
print(sortedSquaredArray(a))

[1, 4, 9, 16, 25]
[1, 4, 9, 25, 36, 64, 81]


In [4]:
#O(n) time | O(n) space
def sortedSquared_Array(array):
    # create new array all 0s
    sorted_squared = [0 for _ in array]
    # two pointers
    left = 0
    right = len(array)-1
    # iterate reserse to fill up form end to start 
    for i in reversed(range(len(array))):
        left_value = array[left]
        right_value = array[right]
        # compare and take bigger value then increase or decrease i
        if abs(left_value) > abs(right_value):
            sorted_squared[i] = left_value * left_value
            left +=1
        else:
            sorted_squared[i] = right_value * right_value
            right -=1
    return sorted_squared



In [5]:
print(sortedSquared_Array(b))
print(sortedSquared_Array(a))

[1, 4, 9, 16, 25]
[1, 4, 9, 25, 36, 64, 81]


## Arrays Medium

- Smallest Difference 

In [6]:
def smallestDifference(arrayOne, arrayTwo):
    result = []
    arrayOne.sort()
    arrayTwo.sort()
    pointer_One = 0
    pointer_Two = 0
    current = float("inf")
    smallest = float("inf")

    while pointer_One < len(arrayOne) and pointer_Two < len(arrayTwo):
        numOne = arrayOne[pointer_One]
        numTwo = arrayTwo[pointer_Two]

        if numOne < numTwo:
            current = numTwo - numOne
            pointer_One += 1
        elif numOne > numTwo:
            current = numOne - numTwo
            pointer_Two += 1
        else:
            return [numOne, numTwo]
        if  smallest > current:
            smallest = current
            result = [numOne, numTwo]
    return result


### Move Element to end:
> array= [2,1,2,2,2,2,3,4,2]
> toMove=2

> output: [1,3,4,2,2,2,2,2,2]

Numbers 1, 3, 4 can be order differently 

In [7]:
#O(n) time | o(1) n len of array
def moveElementToEnd(array, toMove):
    i = 0
    j = len(array)-1

    #as long as i is to the left of j
    while i < j:
        #account for last swap and move j until != toMove
        while i < j and array[j] == toMove:
            j -= 1
        if array[i] == toMove:
            #swap numbers i and j
            array[i], array[j] = array[j], array[i]
        i += 1
    return array
    

In [8]:
a = [2,1,2,2,2,2,3,4,2]
moveElementToEnd(a, 2)

[4, 1, 3, 2, 2, 2, 2, 2, 2]

### Monotonic Array

nonDecresing or nonincresing 
Cool or boolean

[-1, 0, 3,4 6, 7, 8]
True


In [9]:
def isMonotonic(array):
    nonDecresing = True
    nonincresing = True
    
    #compare each num to the prev num
    for i in range(1, len(array)):
        #incresing
        if array[i] > array[i-1]:
            nonDecresing = False
        #decresing
        if array[i] < array[i-1]:
            nonincresing = False
    #whether or not one of these is True
    return nonDecresing or nonincresing

In [10]:
print(a)
print(isMonotonic(a))
print(isMonotonic([-1, 0, 3, 4, 6, 7, 8] ))

[4, 1, 3, 2, 2, 2, 2, 2, 2]
False
True


## Spiral traverse


In [11]:
def spiralTraverse(array):
    spiral = []
    start_row, end_row = 0, len(array)-1
    start_col, end_col = 0, len(array[0])-1

    while start_row <= end_row and start_col <= end_col:
        #first top line
        for col in range(start_col, end_col+1): #end_col inclusive
            spiral.append(array[start_row][col])
        #right most line going down
        for row in range(start_row +1, end_row + 1):
            spiral.append(array[row][end_col])
        #bottom line going left
        for col in reversed(range(start_col, end_col)):
            #when single row case
            if start_row == end_row:
                break
            spiral.append(array[end_row][col])
        #left most line going up
        for row in reversed(range(start_row + 1, end_row)):
            #when single col case
            if start_col == end_col:
                break
            spiral.append(array[row][start_col])
        #inner square
        start_row += 1
        start_col += 1
        end_row -= 1
        end_col -= 1
    return spiral


In [12]:
array = [[1,2,3],
         [8,9,4],
         [7,6,5]]

In [13]:
x = spiralTraverse(array)
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
len(a[3:])

5

## Array of products 

Return the multiplication of all elements 

Array = [5, 4, 1, 2]
Result = [8, 10, 40, 20] 


In [15]:
import math

# [5,1,4,2]
def arrayOfProducts(array):
    result = []

    for i in range(len(array)):
        temp = array[i]
        array[i]=1
        result.append(math.prod(array))
        array[i] = temp
    return result

In [16]:
b = [5,1,4,2] # [8,40,10,20]

In [17]:
arrayOfProducts(b)

[8, 40, 10, 20]

In [18]:
math.prod(b)

40

In [19]:
a = [2,5,3,4]

In [20]:
def firstDuplicateValue(array):

    seen = []
    for i in array:
        if i in seen:
            return i 
        seen.append(i)
#     return 


In [21]:
firstDuplicateValue(a)

In [22]:
2*sum(set(a))-sum(a)

14

In [23]:
a = np.arange(9)

In [24]:
a = a.reshape(3,3)


In [25]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
def spiralTraverse(array):
    a = np.array(array)
    a = a.flatten()
    print(a)

In [27]:
spiralTraverse(array)

[1 2 3 8 9 4 7 6 5]


In [28]:
print(a.flatten())

[0 1 2 3 4 5 6 7 8]


In [29]:

a = np.array(a)

In [30]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Longest Peak

In [31]:
def longestPeak(array):
    #find the first peak
    #extend its tails and save its length
    #find the next peak, expand its tails and compare with current len
    #return the longest
    longest = 0
    i = 1 #bc need to compare to prev
    while i < len(array)-1:
        # peak when both adjacent are smaller
        peak = array[i -1] < array[i] and array[i] > array[i+1]
        if not peak:
            i += 1
            continue
        #left tail of the peaks/ stop when reaches the 0th index
        left_i = i - 2
        while left_i >= 0 and array[left_i] < array[left_i + 1]:
            left_i -= 1
        #rigth tail / stop when reach the last index
        right_i = i + 2
        while right_i < len(array) and array[right_i] < array[right_i - 1]:
            right_i += 1

        current_peak = right_i - left_i - 1
        longest = max(longest, current_peak)
        i = right_i # look for next peak staring from right i
    return longest


In [32]:
print(longestPeak([1,4,2,4,6,8,5,3,0]))# idx2 to idx8
print(longestPeak([1,4,0]))# idx2 to idx8

7
3


### FIrst Duplicate Value

In [33]:
def firstDuplicateValue(array):
    for value in array:
        abs_value = abs(value)
        if array[abs_value -1] < 0: # if negative -> duplicate found
            return abs(value)
        #if not negative set the value to negative
        array[abs_value - 1] *= -1
    return -1
# O(n)time worse case it iterates through entire array
#O(1)space using original array no extra memory 

In [34]:
print(firstDuplicateValue([1,4,2,4,6,8,5,3,0]))
print(firstDuplicateValue([1,4,2,0]))
print(firstDuplicateValue([1,0,1,0]))

4
-1
1


### Overlapping Intervals

In [35]:
def mergeOverlappingIntervals(intervals):
    #start by sorting the starting time
    sortedStartingTime = sorted(intervals, key = lambda x: x[0])

    mergedIntervals = []
    current = sortedStartingTime[0]
    #append the first interval to compare to
    mergedIntervals.append(current)

    for nextInterval in sortedStartingTime:
        #only care about the end time
        _, currentEnd = current
        nextStarting, nextEnd = nextInterval
        #if overlap, take the max
        if currentEnd >= nextStarting:
            current[1]= max(currentEnd, nextEnd)
        else:
            current = nextInterval
            #if not then just add it to list
            mergedIntervals.append(current)
    return mergedIntervals

In [36]:
print(mergeOverlappingIntervals([[1,2],[2,3],[1,4],[5,8]]))
print(mergeOverlappingIntervals([[0,0],[0,0]]))

[[1, 4], [5, 8]]
[[0, 0]]
